server:
  port: 8000

spring:
  application:
    name: nutrixpert-api

  datasource:
    url: jdbc:oracle:thin:@oracle:1521/XEPDB1
    username: nutrixpert
    password: NutriXpert2025!
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      initialization-fail-timeout: 120000

  jpa:
    hibernate:
      ddl-auto: none   # use migrações (Flyway). Se quiser gerar esquema em dev: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        jdbc.lob.non_contextual_creation: true
  # Devtools para hot reload
  devtools:
    restart:
      enabled: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,flyway
  endpoint:
    health:
      show-details: when-authorized
    flyway:
      enabled: true

# Configurações do Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
