server:
  port: 8000

spring:
  application:
    name: nutrixpert-api

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@oracle:1521/XEPDB1}
    username: ${SPRING_DATASOURCE_USERNAME:nutrixpert}
    password: ${SPRING_DATASOURCE_PASSWORD:NutriXpert2025!}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      initialization-fail-timeout: 120000
      connection-test-query: "SELECT 1 FROM DUAL"
      connection-timeout: 30000
      validation-timeout: 5000
      max-lifetime: 1800000
      minimum-idle: 2
      maximum-pool-size: 10
      leak-detection-threshold: 2000

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        jdbc.lob.non_contextual_creation: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: false

llm:
  api:
    url: ${LLM_API_URL:https://api.openai.com/v1/chat/completions}
    key: ${LLM_API_KEY:}
    model: ${LLM_MODEL:gpt-4o-mini}
  optimization:
    model: ${LLM_OPTIMIZATION_MODEL:${LLM_MODEL:gpt-4o-mini}}
  request:
    timeout:
      seconds: ${LLM_REQUEST_TIMEOUT_SECONDS:30}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true

llm:
  api:
    url: ${LLM_API_URL:https://api.openai.com/v1/chat/completions}
    key: ${LLM_API_KEY:}
    model: ${LLM_MODEL:gpt-4o-mini}
  optimization:
    model: ${LLM_OPTIMIZATION_MODEL:${LLM_MODEL:gpt-4o-mini}}
  request:
    timeout:
      seconds: ${LLM_REQUEST_TIMEOUT_SECONDS:30}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
