services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: nutrisecret
      POSTGRES_USER: postgres
      POSTGRES_DB: nutrixpert
      TZ: America/Sao_Paulo
    volumes:
      - nutrixpert_db_data:/var/lib/postgresql/data
      # scripts de init da sua app (criam usuário/banco)
      # - ./initdb:/docker-entrypoint-initdb.d:ro
    shm_size: "256mb"
    restart: always
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - postgres
    environment:
      TZ: America/Sao_Paulo
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nutrixpert
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: nutrisecret
      MAVEN_OPTS: "-Xms128m -Xmx256m"
      SPRING_BOOT_JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx512m -XX:MaxRAMPercentage=60"
      JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF-8 -Duser.timezone=America/Sao_Paulo"
      SPRING_DATASOURCE_HIKARI_INITIALIZATION-FAIL-TIMEOUT: "60000"
    working_dir: /workspaces
    command: [ "bash", "-lc", "sleep infinity" ]
    volumes:
      - ..:/workspaces:cached
      - maven-repo:/home/vscode/.m2
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

volumes:
  nutrixpert_db_data:
  maven-repo:
